In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import pandas as pd

plt.style.use('dark_background')

In [2]:
raw_data = pd.DataFrame(np.random.choice([0, 1], size=(100, 2)), columns=['A', 'B'])
df = pd.crosstab(raw_data['A'], raw_data['B'])  # contingency table
df['total'] = df.sum(axis=1)
df.loc['total'] = df.sum()

df

B       0   1  total
A
0      21  35     56
1      24  20     44
total  45  55    100

### Teste de associação

In [3]:
a = 0.05
chi2_stat, p_val, dof, ex = stats.chi2_contingency(df.iloc[:-1, :-1])
print(f"Chi2 Stat: {chi2_stat}, P-value: {p_val}, Degrees of Freedom: {dof}")
if p_val < a:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Chi2 Stat: 2.244851108487471, P-value: 0.13405981174399972, Degrees of Freedom: 1
Fail to reject the null hypothesis

In [4]:
df.iloc[:-1, :-1]

B   0   1
A
0  21  35
1  24  20

### Teste de aderência

In [5]:
df.iloc[:-1, :-1].values.flatten()

array([21, 35, 24, 20])

In [6]:
esp = np.array([25, 25, 25, 25])
chi2_stat, p_val = stats.chisquare(df.iloc[:-1, :-1].values.flatten(), f_exp=esp)
print(f"Chi2 Stat: {chi2_stat}, P-value: {p_val}")
if p_val < a:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Chi2 Stat: 5.68, P-value: 0.12826035058754304
Fail to reject the null hypothesis

### Associação 1xn

In [7]:
contingency_df = pd.DataFrame({
    'Basic': [100, 120],
    'Default': [150, 100],
    'Premium': [50, 80],
})
contingency_df.loc['total'] = contingency_df.sum()
contingency_df['total'] = contingency_df.sum(axis=1)

contingency_df.index = ['Male', 'Female', 'total']
contingency_df

        Basic  Default  Premium  total
Male      100      150       50    300
Female    120      100       80    300
total     220      250      130    600

In [8]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(contingency_df.iloc[:-1, :-1])
print(f"Chi2 Stat: {chi2_stat}, P-value: {p_val}, Degrees of Freedom: {dof}")
if p_val < a:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Chi2 Stat: 18.74125874125874, P-value: 8.518975561410697e-05, Degrees of Freedom: 2
Reject the null hypothesis